export const currenciesMap = {
  USD: { name: 'Estados Unidos', flag: '🇺🇸' },
  BRL: { name: 'Brasil', flag: '🇧🇷' },
  EUR: { name: 'Zona do Euro', flag: '🇪🇺' },
  GBP: { name: 'Reino Unido', flag: '🇬🇧' },
  JPY: { name: 'Japão', flag: '🇯🇵' },
  CAD: { name: 'Canadá', flag: '🇨🇦' },
  AUD: { name: 'Austrália', flag: '🇦🇺' },
  CHF: { name: 'Suíça', flag: '🇨🇭' },
  CNY: { name: 'China', flag: '🇨🇳' },
  ARS: { name: 'Argentina', flag: '🇦🇷' },
  CLP: { name: 'Chile', flag: '🇨🇱' },
  COP: { name: 'Colômbia', flag: '🇨🇴' },
  MXN: { name: 'México', flag: '🇲🇽' },
  UYU: { name: 'Uruguai', flag: '🇺🇾' },
  PYG: { name: 'Paraguai', flag: '🇵🇾' },
  PEN: { name: 'Peru', flag: '🇵🇪' },
  INR: { name: 'Índia', flag: '🇮🇳' },
  RUB: { name: 'Rússia', flag: '🇷🇺' },
  ZAR: { name: 'África do Sul', flag: '🇿🇦' },
  KRW: { name: 'Coreia do Sul', flag: '🇰🇷' },
  SEK: { name: 'Suécia', flag: '🇸🇪' },
  NOK: { name: 'Noruega', flag: '🇳🇴' },
  DKK: { name: 'Dinamarca', flag: '🇩🇰' },
  NZD: { name: 'Nova Zelândia', flag: '🇳🇿' },
  SGD: { name: 'Singapura', flag: '🇸🇬' },
  HKD: { name: 'Hong Kong', flag: '🇭🇰' },
  TRY: { name: 'Turquia', flag: '🇹🇷' },
  ILS: { name: 'Israel', flag: '🇮🇱' },
  SAR: { name: 'Arábia Saudita', flag: '🇸🇦' },
  AED: { name: 'Emirados Árabes', flag: '🇦🇪' },
  GYD: { name: 'Guiana', flag: '🇬🇾' },
  IDR: { name: 'Indonésia', flag: '🇮🇩' },
  MYR: { name: 'Malásia', flag: '🇲🇾' },
  PHP: { name: 'Filipinas', flag: '🇵🇭' },
  THB: { name: 'Tailândia', flag: '🇹🇭' },
  VND: { name: 'Vietnã', flag: '🇻🇳' },
  PLN: { name: 'Polônia', flag: '🇵🇱' },
  HUF: { name: 'Hungria', flag: '🇭🇺' },
  CZK: { name: 'República Tcheca', flag: '🇨🇿' },
};